<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>MabiCommerceNewLife</AssemblyName>
    <RootNamespace>MabiCommerceNewLife</RootNamespace>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
    <PackageReference Include="TesseractOCR" Version="5.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Include="src\App.xaml" />
    <Page Include="src\**\*.xaml" Exclude="src\App.xaml" />
    <Compile Include="src\**\*.cs" />
    <None Include="LICENSE;THIRD-PARTY-NOTICES.txt" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Data\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>